apiVersion: v1
kind: Pod
metadata:
  name: my-pod-example # Name defines the name of the pod to be created
spec:
  containers:
    - name: frontend
      image: nginx
      ports:
        - containerPort: 80