apiVersion: v1
kind: Service
metadata:
  name: my-service-example # Service Name goes here
spec:
  type: ClusterIP # ClusterIP is the default. NodePort and LoadBalancer are also available.
  ports:
  - protocol: TCP
    port: 80 # Update this port for what should be exposed
    targetPort: 9376 # Update this port for the target pod. This line is not necessary if the exposed port and the target port are the same.
  selector:
    app: # Target App Name goes here